'''
Created Dec. 1 2015
@author Carl J. Raymond
'''


# 0 0 0
# 1 0 0
# 1 1 0
# 1 1 1
# 1 1 2
# 1 1 3
# 1 2 0
# 1 2 1
# 1 2 2
# 1 2 3
# 1 3 0
# 1 3 1
# 1 3 2
# 1 3 3
# 2 0 0
# 2 1 0
# 2 1 1
# 	 

# Generates words in sequence
def lexv(alphabet, length):

	# The augmented alphabet includes the empty string at position 0
	size = len(alphabet)
	augmented = [''] + alphabet
	
	# Index is a list of indices of characters in the augemented alphabet.
	# Start by creating an index of all zeroes, which corresponds to an empty string.
	index = [0] * length

	# Iterate to the next index by finding the increment point.
	# When the index contains one or more zeroes, the leftmost zero is the increment point.
	# The zeroes are always contiguous, and at the right end of the list, so the first zero from the
	# left will be in increment point.
	# When the index contains no zeroes, the increment point is the rightmost digit that is less than
	# the maximum value of size.
	# When neither condition is satisfied, the generator is done.
	#
	# Once the increment point is found, the next index is generated by incrementing the digit at
	# the increment point, and filling the following array elements with zero.
	# The corresponding word is generated by concatenating the characters in the alphabet corresponding
	# to the index values.

	while True:
		# Find increment point
		if 0 in index:
			pos = index.index(0)
		else:
			for pos in xrange(length-1, -1, -1):
				if index[pos] != size:
					break
			else:
				return
				
		# Increment at that point, and set subsequent values to 0
		index[pos] += 1
		for z in xrange(pos+1, length):
			index[z] = 0
		
		yield "".join(augmented[p] for p in index)

	
with open("data/rosalind_lexv.txt") as spec:
    alphabet = spec.readline().split();
    length = int( spec.readline());

print alphabet
print length

with open("data/rosalind_lexv.out", "w+") as result:
	for index in lexv(alphabet, length):
		result.write(index)
		result.write('\n')
